#!/bin/bash
 
__ping="/bin/ping"
__ftp="/usr/bin/ftp -An"
__find="/bin/find"

for __ in "$(dirname $0)/lib-"* ; do . "${__}" ; done



show_usage()
{
    echo "Usge: $0 -u user -p password -d direcotory -h host1,host2..." 1>&2
    exit 1
}


generate_connect_string()
{
    local _u="$1"
    local _h="$2"
    local _p="$3"

    if [ -z "${_u}" -o -z "${_h}" -o -z "${_p}" ]
    then
        generate_disconnect_string
        return 1
    fi

    cat <<COMMAND
open ${_h}
user ${_u} ${_p}
COMMAND
    return $?
}


generate_disconnect_string()
{
    echo "bye"
    return $?
}


generate_multi_string()
{
    local _command="$1"; shift
    local _string=

    if [ -z "${_command}" ]
    then
        return 1
    fi

    for _target in $@
    do
        _string="${_string}${_string:+\n}${_command} ${_target} $(basename ${_target})"
    done

    echo -e "${_string}"
    return $?
}


generate_multi_mkdir_string()
{
    generate_multi_string "mkdir" "$@"
    return $?
}


generate_multi_put_string()
{
    generate_multi_string "put" "$@"
    return $?
}


list_files_in()
{
    local _directory="$1"

    ${__find} "${_directory}" -type f
    return $?
}


list_all_subdirectories_in()
{
    local _directory="$1"

    ${__find} "${_directory}" -type d
    return $?
}



# MAIN PROCESS
_host=
_user=
_password=
_directory_source=
_directory_destination=
while getopts h:u:p:s:d: OPT
do
    case "${OPT}" in
    h)
        _host="${OPTARG}"
        ;;

    u)
        _user="${OPTARG}"
        ;;
 
    s)
        _directory_source="${OPTARG}"
        ;;

    d)
        _directory_destination="${OPTARG}"
        ;;
 
    p)
        _password="${OPTARG}"
        ;;
 
    \?)
        show_usage
        ;;
    esac
done
 
 
[ -z "${_host}" ] && log_err_message "No host is specified." && exit 255
[ -z "${_directory_source}" ] && log_err_message "Source directory is not specified." && exit 255
[ -z "${_password}" ] && log_err_message "Password is not set." && exit 255

_user="${_user:-$USER}"
_directory_target="${_directory_target:-.}"

log_info_message "Login user is ${_user}."
log_info_message "Source directory is localhost:${_directory_source}."
log_info_message "Destination directory is ${_host}:${_directory_destination}."


_n_warns=0
{
    generate_connect_string "${_user}" "${_host}" "${_password}"

    #generate_multi_put_string $(list_subdirectories_in "${_directory_source}")

   # echo "ls"
   # for _f in $(find "${_directory}" -type f)
   # do
   #     generate_multi_put_string "${_f}"
   # done
    generate_disconnect_string
}
#
#} > >(${_ftp})
 
log_info_message "Process is finished with ${_n_warns} warning(s)."
exit 0

